Updated readme.md
freeCodeCamp/CamperChan-discord pull request #14
Opened 2020-05-13 12:35 UTC by Twaha-Rahman

Updated the README.md file with all the required info to get started.

This PR should close both #1 and #3

2020-05-13 12:58 UTC, Twaha-Rahman commented
This PR should also close #8 . As I have added a `Disclaimer` too

2020-05-13 18:01 UTC, bradtaniguchi requested changes
We **may** want to end up changing where the files are saved to another branch in `git` using [this approach](https://medium.com/@minamimunakata/how-to-store-images-for-use-in-readme-md-on-github-9fb54256e951). This way when someone downloads the repo they don't have to download all the extra png/gif files.

I'd say the easiest way to integrate that approach at this point is to **remove the image files, but leave the links in the README as is**, and I'll add a branch following the above approach and add the images and "fix" the links.
(I already downloaded the images you used locally)

So just remove/update the disclaimer as a PR has already added this, but leave the rest of the docs as they look pretty good. @nhcarrigan Would you like to review the updates to the README to check for typos, any syntax issues (I only quickly skimmed em ;D)

2020-05-13 18:36 UTC, nhcarrigan commented
I have to step out for a bit, but I see a couple of typos and some grammar changes. I'll add some comments when I get back.

2020-05-13 22:13 UTC, Twaha-Rahman commented
> I'd say the easiest way to integrate that approach at this point is to **remove the image files, but leave the links in the README as is**, and I'll add a branch following the above approach and add the images and "fix" the links.

I removed **all** the images along with the folder

> So just remove/update the disclaimer as a PR has already added this, but leave the rest......

Reverted and removed the disclaimer

All set for a review! 😃

2020-05-13 22:33 UTC, nhcarrigan commented on README.md
> +4. Create a new branch on the cloned repo and swith to it
Typo: swith => switch

2020-05-13 22:51 UTC, Twaha-Rahman commented on README.md
> +4. Create a new branch on the cloned repo and swith to it
Fixed it!

2020-05-13 23:33 UTC, nhcarrigan commented
@bradtaniguchi You're good to merge this... there's a couple of grammar pieces I want to tweak but it'd be easier to do it as a new pull request I think

2020-05-13 23:41 UTC, Ryuno-Ki commented
@nhcarrigan Are you going to fix the conflicting file?

2020-05-13 23:44 UTC, bradtaniguchi commented
I was waiting for @Twaha-Rahman to fix the conflicts (as its their PR) before merging. Otherwise I'll resolve it myself later today and merge it.

2020-05-14 00:37 UTC, Twaha-Rahman commented
@bradtaniguchi Sorry I couldn't reply earlier....was doing other stuffs... removed the merge conflict< good to go!

2020-05-14 00:46 UTC, bradtaniguchi commented
> @bradtaniguchi Sorry I couldn't reply earlier....was doing other stuffs... removed the merge conflict, good to go!

No worries! No rush at all :D

2020-05-14 00:47 UTC, merged